const selamlamaTetikleyicileri = [
    { tip: 'selam', kelimeler: ["selam","selamlar","hey","heyy","heyyy","merhaba","mrb","slm","sa","slmm","slmlar","selamünaleyküm","şelom","selaam","selaamlar","selamm","hiii","hello","merhabalaar","meraba","meb","selamke","selamlar herkese","selamin aleykum"] },
    { tip: 'günaydın', kelimeler: ["günaydın","gunaydin","günaydınn","g.a","ga","günaydınlar","hayırlı sabahlar","sabahlar hayrolsun","günaydın herkese","iyi sabahlar","sabah sabah","gnydn","guunydin","uykucu","günaydınnn","sabaho","sabah şerifleriniz hayrolsun","hayirli sabahlar","hayırlı sabahlar herkese","uyandım","kalktım","günaydınlar herkese"] },
    { tip: 'tünaydın', kelimeler: ["tünaydın","tunaydin","tünaydınn","tn","tünaydınlar","tunaydın","iyi öğlenler","iyi oglenler","öğlen","oglen","tünaydınlar herkese","tnaydin","tnaydın","tunaydinlar","tunaydınn","iyi öğleden sonralar","öğle vakti","ogle vakti","öğle","ogle"] },
    { tip: 'iyi akşamlar', kelimeler: ["iyi akşamlar","iyi aksamlar","iyi aksam","iyi akşam","i.a.","ia","hayırlı akşamlar","hayirli aksamlar","aksamlar","akşamlar","iyi akşamlar herkese","iyi aksamlar herkese","hayırlı akşamlar herkese","iyiakşamlar","iyiaksamlar","aksam aksam","akşam akşam","tünaydın akşam","hayrolsun akşam"] },
    { tip: 'iyi geceler', kelimeler: ["iyi geceler","iyi gece","i.g.","ig","hayırlı geceler","hayirli geceler","iyi geceler herkese","geceler","iyigeceler","iyigeceler herkese","geceniz hayrolsun","iyi geceer","iyi gecelerr","iyi geceleriniz olsun","geceler geceler","gece gece","hayırlı geceler herkese","tatlı rüyalar geceler"] },
    { tip: 'iyi uykular', kelimeler: ["iyi uykular","tatlı rüyalar","tatli ruyalar","iyi dinlenmeler","iyi uykularr","tatlı rüyalar dilerim","iyi dinlenmeler dilerim","uykular","dinlenmeler","deliksiz uyku","iyi uykular herkese","guzel ruyalar","güzel rüyalar","mışıl mışıl","yattım ben","ben kaçar uyumaya","uyumaya gidiyorum","uyuyorum","uykum geldi","yatıyorum","zıbarıyorum"] },
    { tip: 'hayırlı cuma', kelimeler: ["hayırlı cumalar","hayirli cumalar","hayırlı cuma","hayirli cuma","h.c.","hc","cuma gününüz mübarek olsun","cumalar","hayırlı cumalar herkese","cumanız mübarek olsun","hayırlı cumalar dilerim","cuma mesajı","cumanız müb","hayirli cumalar herkese","cuma bereketi","hayırlı nurlu cumalar","nurlu cumalar","hayırlı cumalarımız olsun","hayırlıcumalar","hayirlicumalar"] },
    { tip: 'selamun aleyküm', kelimeler: ["selamun aleyküm","selamın aleyküm","selamunaleyküm","s.a.","sa","selamün aleyküm","selamin aleykum","selamun aleykum","selamünaleyküm","s.a.v","s.a.ve","selamun aleyküm herkese","selamın aleyküm herkese","s.a.aleyküm","saaa","selamnaleykum","selamunaleykum","esselamu aleyküm","esselamun aleyküm","selamun aleyküm beyler"] },
    { tip: 'iyi günler', kelimeler: ["iyi günler","iyi gunler","i.g.","ig","iyi günler herkese","iyigünler","iyigunler","iyi günler dilerim","hayırlı günler","hayirli gunler","güzel günler","gunler","günler","iyi günleriniz olsun","gününüz güzel geçsin","gununuz guzel gecsin","hayırlı günler herkese","iyi günler dilerim herkese","güzel günler dilerim"] },
    { tip: 'nasılsın', kelimeler: ["nasılsın","nasılsınız","naber","ne haber","n'aber","nbr","nabers","nasilsin","nasilsiniz","keyifler nasıl","keyifler nasil","nasıl gidiyor","nasil gidiyor","nasıl gidiyo","nasil gidiyo","nettin","ne var ne yok","nevar neyok","nasılsın bakalım","nasılsın canım","nasılsın dostum","nasılsınız efendim","keyifler yerinde mi"] },
    { tip: 'ne yapıyorsun', kelimeler: ["ne yapıyorsun","ne yapıyorsunuz","napıyorsun","napıyon","napıyosun","nepiyorsun","ne yapıyon","ne yapiyorsun","ne yapiyorsunuz","nörüyon","noruyon","napıyonuz","napıyosunuz","ne iş","neyle meşgulsün","neyle mesgulsun","ne yapmaktasınız","napıon","napion","ne ediyon","ne ediyorsun","napıyorsun bakalım","napıyosun bakalım"] },
    { tip: 'iyi bayramlar', kelimeler: ["iyi bayramlar","hayırlı bayramlar","hayirli bayramlar","bayramınız mübarek","bayramınız mübarek olsun","bayraminiz mubarek olsun","bayramlar","iyi bayramlar herkese","hayırlı bayramlar herkese","bayramınız kutlu olsun","bayraminiz kutlu olsun","mutlu bayramlar","ramazan bayramı","kurban bayramı","bayram harçlığı","bayramlaşalım","bayram şekerleri","iyi bayramlar dilerim","hayırlı bayramlar dilerim","bayram kutlu olsun"] },
    { tip: 'hoş geldin', kelimeler: ["hoş geldin","hoş bulduk","hoş geldiniz","hos geldin","hos geldiniz","hos bulduk","hoşgeldin","hoşgeldiniz","hoşbulduk","hoş bulduk herkese","hoşgeldiniz herkese","hosgeldin","hosgeldiniz","hosbulduk","hoş bulduk efenim","sefalar getirdiniz","hoş geldin sefa geldin","hoşgeldin canım","hoş geldin dostum","hoş geldin kanka"] },
    { tip: 'görüşürüz', kelimeler: ["görüşürüz","gorusuruz","güle güle","gule gule","g.g.","gg","bb","byebye","bye","bby","hoşça kal","hoşçakal","hosca kal","hoscakal","bye bye","bay bay","kaçtım ben","kactim ben","görüşmek üzere","gorusmek uzere","hadi eyvallah","eyvallah","ben kaçar","ben kacar","görüşürüz herkese","kendinize iyi bakın"] },
    { tip: 'iyiyim', kelimeler: ["iyiyim","iyi","süperim","superim","süper","super","iyidir","çok şükür","cok sukur","bomba gibiyim","harikayım","harika","bomba","idare eder","iyiyim şükür","iyiyim sukur","fena değil","fena degil","iyiyiz","iyiyim çok şükür","iyiyim elhamdülillah","her şey yolunda","hersey yolunda","bomba gibiyiz"] },
];

const cevapHavuzu = {
    'selam': [
        (u) => `Selam ${u}! 👋 Nasıl gidiyor, her şey yolunda mı?`,
        (u) => `Hey hey, ${u} gelmiş! 😄 Ne var ne yok?`,
        (u) => `Merhaba ${u}! 🌟 Seni görmek güzel!`,
        (u) => `Selam ${u}! ✨ Seni gördüm, biraz daha güzelleşti burası 😄`,
        (u) => `Heyy ${u}! 😊 Naber, ne alemdesin?`,
        (u) => `Ooo selam ${u}, hoş geldin!`,
        (u) => `Merhabalar ${u}, günün nasıl geçiyor?`,
        (u) => `Selamlar ${u}! Umarız keyfin yerindedir.`,
        (u) => `Hey ${u}, buralarda mısın?`,
        (u) => `Selammm ${u}! Nasılsın bakalım?`,
        (u) => `Merhaba ${u}! İyi ki geldin.`,
        (u) => `Aaa ${u} gelmiş, selamlar!`,
        (u) => `Selam ${u}! Nasıl hissediyorsun bugün?`,
        (u) => `Vay vay vay, ${u} selamlar!`,
        (u) => `Merhabalar efenim ${u}, hoş geldiniz.`,
        (u) => `Selamın başım üstüne ${u}! Naber?`,
        (u) => `Selam dostum ${u}! Ne haber?`,
        (u) => `Büyük selamlar ${u}! Her şey umarım harikadır.`,
        (u) => `Selam sana da ${u}!`,
        (u) => `Merhaba ${u}! Keyifli sohbetler dilerim.`,
        (u) => `Heyy ${u}! Gözümüz yollarda kalmıştı.`,
        (u) => `Selammm ${u}, ne yapıyorsun?`,
        (u) => `Selam canım ${u}, iyi misin?`,
        (u) => `Selamlar selamlar ${u}! Nasılsın?`,
        (u) => `Merhaba ${u}, neşen bol olsun!`,
        (u) => `Selamın aleyküm de derdim ama sana selam diyeyim ${u}! 👋`,
        (u) => `Hey ${u}, naber, her şey tıkırında mı?`,
        (u) => `Ooo selamlar ${u}, gözümüz aydın!`,
        (u) => `Merhabalaaar ${u}, hoş geldin sefalar getirdin!`,
        (u) => `Selaaam ${u}, keyifler nasıl?`,
    ],
    'günaydın': [
        (u) => `Günaydın ${u}! ☀️ Umarım güzel bir gün geçirirsin!`,
        (u) => `Günaydın ${u}! 🌅 Yeni bir gün, yeni fırsatlar!`,
        (u) => `Günaydın ${u} ☕ Kahveni al, güzel bir gün seni bekliyor!`,
        (u) => `Sabah şeriflerin hayrolsun ${u}! Günaydın!`,
        (u) => `Günaydınlar efenim ${u}, uyanabildik mi?`,
        (u) => `Ooo günaydın ${u}, erkencisin bugün!`,
        (u) => `Günaydın ${u}! Harika bir gün geçirmen dileğiyle.`,
        (u) => `Sana da günaydın ${u}! Enerjin bol olsun.`,
        (u) => `Günaydın ${u}! Güneş bugün senin için parlasın.`,
        (u) => `Erkenci kuş ${u}, günaydın!`,
        (u) => `Günaydın ${u}! Uykunu alabildin mi?`,
        (u) => `Hayırlı sabahlar ${u}, günün aydın olsun.`,
        (u) => `Günaydınlar ${u}! Şahane bir sabah dilerim.`,
        (u) => `Sıcacık bir çay/kahve eşliğinde günaydın ${u}!`,
        (u) => `Günaydın ${u}! Bugün harika şeyler başaracaksın.`,
        (u) => `Neşe dolu bir sabah dilerim ${u}, günaydın!`,
        (u) => `Günaydın ${u}! Gözünü aç, yeni güne başla!`,
        (u) => `Günün aydın, neşen bol olsun ${u}!`,
        (u) => `Sabahlar hayrolsun ${u}, uyan bakalım!`,
        (u) => `Uykucu ${u}, günaydınlar!`,
        (u) => `Günaydın ${u}! Haydi bakalım yeni bir gün.`,
        (u) => `Sana özel günaydın ${u}, iyi ki varsın.`,
        (u) => `Günaydın ${u}! Mutlu sabahlar.`,
        (u) => `Her şeyin gönlünce olduğu bir gün olsun, günaydın ${u}.`,
        (u) => `Kalk kalk ${u}, günaydın!`,
        (u) => `Günün en güzel anı sabahlar, günaydın ${u}!`,
        (u) => `Tatlı sabahlar ${u}, günaydın!`,
        (u) => `Günaydın ${u}! Enerji dolu bir gün olsun.`,
        (u) => `Bol bereketli bir gün olsun ${u}, günaydın!`,
        (u) => `Sana kocaman bir günaydın ${u}!`,
    ],
    'tünaydın': [
        (u) => `Tünaydın ${u}! 🌤️ Günün nasıl geçiyor?`,
        (u) => `Tünaydın ${u} 😊 Öğleden sonranın keyfini çıkar!`,
        (u) => `Sana da tünaydın ${u}! Enerjin düşmesin.`,
        (u) => `Tünaydınlar ${u}! Umarım günün yarısı harika geçmiştir.`,
        (u) => `Tünaydın ${u}! Öğle yemeğini yedin mi?`,
        (u) => `İyi öğlenler ${u}! Dinlenmeyi unutma.`,
        (u) => `Tünaydın ${u}! Keyifli vakitler.`,
        (u) => `Günün tam ortasından tünaydın ${u}!`,
        (u) => `Tünaydın ${u}! İşler nasıl gidiyor?`,
        (u) => `Tünaydın efenim ${u}, kolay gelsin.`,
        (u) => `Hayırlı öğlenler ${u}, tünaydınlar!`,
        (u) => `Öğle molası vakti! Tünaydın ${u}.`,
        (u) => `Tünaydın ${u}! Zaman ne çabuk geçiyor değil mi?`,
        (u) => `Sıcacık tünaydınlar ${u}!`,
        (u) => `Tünaydın ${u}! Güzel bir öğleden sonra dilerim.`,
        (u) => `Selamlar, tünaydınlar ${u}!`,
        (u) => `Tünaydın ${u}, umarım günün verimli geçiyordur.`,
        (u) => `Tünaydın ${u}! Gülümsemeyi unutma.`,
        (u) => `Güneşi tepede gördük, tünaydın ${u}!`,
        (u) => `Sana da tünaydın ${u}, güzel insan.`,
        (u) => `İyi öğleden sonraları ${u}!`,
        (u) => `Tünaydın ${u}, harikasın bugün!`,
        (u) => `Kocaman bir tünaydın sana ${u}!`,
        (u) => `Öğlen olmuş, tünaydınlar ${u}!`,
        (u) => `Tünaydın ${u}, çay molası verdin mi?`,
        (u) => `Tünaydın ${u}! Yoruldun mu biraz?`,
        (u) => `Huzurlu bir öğle vakti dilerim ${u}, tünaydın.`,
        (u) => `Enerjik bir öğleden sonra için tünaydın ${u}!`,
        (u) => `Tünaydın ${u}! Her şey yolunda mı?`,
        (u) => `Günün en verimli saatleri, tünaydın ${u}!`,
    ],
    'iyi akşamlar': [
        (u) => `İyi akşamlar ${u}! 🌆 Günün nasıl geçti?`,
        (u) => `İyi akşamlar ${u} 🌇 Huzurlu bir akşam dilerim!`,
        (u) => `İyi akşamlar ${u}! ✨ Keyifli bir akşam geçirmeni dilerim!`,
        (u) => `Sana da iyi akşamlar ${u}! Ne yapıyorsun?`,
        (u) => `Hayırlı akşamlar ${u}! Günün yorgunluğunu atma vakti.`,
        (u) => `İyi akşamlar ${u}! Çaylar/Kahveler benden.`,
        (u) => `Günün yorgunluğunu atmak için güzel bir akşam olsun ${u}!`,
        (u) => `Huzurlu akşamlar dilerim ${u}!`,
        (u) => `İyi akşamlar ${u}! Neler yapıyorsun bu akşam?`,
        (u) => `Güzel akşamlar ${u}! Keyfin yerindedir umarım.`,
        (u) => `Sakin ve dingin bir akşam dilerim ${u}.`,
        (u) => `İyi akşamlar ${u}! Bugün de bitti sayılır.`,
        (u) => `İyi akşamlar ${u}! Akşamın tadını çıkar.`,
        (u) => `Sana da iyi akşamlar ${u}! Nasılsın?`,
        (u) => `Keyifli akşamlar ${u}! Bir şeyler izliyor musun?`,
        (u) => `Hayırlı akşamlar ${u}, günün stresini at gitsin.`,
        (u) => `İyi akşamlar ${u}! Mutlu bir geceye hazırlık.`,
        (u) => `Güzel bir akşam seninle olsun ${u}!`,
        (u) => `Akşam şeriflerin hayrolsun ${u}!`,
        (u) => `İyi akşamlar efenim ${u}, hoş geldiniz.`,
        (u) => `Sıcacık yuvanda iyi akşamlar ${u}!`,
        (u) => `İyi akşamlar ${u}! Yıldızlar senin için parlasın.`,
        (u) => `İyi akşamlar ${u}, kahve molası vakti!`,
        (u) => `Karanlık çöktü, iyi akşamlar ${u}!`,
        (u) => `Akşamınız güzel geçsin ${u}!`,
        (u) => `Neşe dolu bir akşam dilerim ${u}!`,
        (u) => `Harika bir akşam geçir ${u}!`,
        (u) => `İyi akşamlar ${u}, dinlenmeyi hak ettin.`,
        (u) => `Güzel dostlara iyi akşamlar, sana da ${u}!`,
        (u) => `Akşamın sessizliği ve huzuru seninle olsun ${u}!`,
    ],
    'iyi geceler': [
        (u) => `İyi geceler ${u}! 🌙 Tatlı rüyalar!`,
        (u) => `İyi geceler ${u} 😴 Dinlendirici bir uyku dilerim!`,
        (u) => `Sana da iyi geceler ${u}, güzel uyu.`,
        (u) => `Hayırlı geceler ${u}, rüyanda beni gör!`,
        (u) => `İyi geceler ${u}! Yarın yeni ve güzel bir gün olacak.`,
        (u) => `Gecen xeyrə qalsın ${u}! Tatlı uykular.`,
        (u) => `İyi geceler ${u}! Gözlerini dinlendir artık.`,
        (u) => `Gecenin sessizliği sana huzur versin ${u}, iyi geceler.`,
        (u) => `Sana huzurlu bir gece dilerim ${u}.`,
        (u) => `İyi geceler ${u}! Mışıl mışıl uyu.`,
        (u) => `Geceler geceler... İyi geceler ${u}!`,
        (u) => `Tatlı rüyalar ${u}, iyi geceler!`,
        (u) => `İyi geceler ${u}! Günün tüm stresi geride kalsın.`,
        (u) => `Yarın görüşmek üzere ${u}, iyi geceler!`,
        (u) => `Huzurla uyu ${u}, iyi geceler.`,
        (u) => `İyi geceler ${u}! Melekler başucunda olsun.`,
        (u) => `Güzel rüyalar gör ${u}, iyi geceler.`,
        (u) => `Gece uzun, uyku tatlı olsun ${u}!`,
        (u) => `İyi geceler ${u}, yatağın pamuk gibi olsun.`,
        (u) => `Hadi bakalım, yatak vakti geldi ${u}! İyi geceler.`,
        (u) => `Sana da iyi geceler ${u}, dinlen iyice.`,
        (u) => `Bol bol dinlenmeli bir gece olsun ${u}.`,
        (u) => `Geceniz güzel, uykunuz derin olsun ${u}.`,
        (u) => `İyi geceler ${u}, yıldızlar seni korusun.`,
        (u) => `İyi geceler ${u}, karanlık sana huzur getirsin.`,
        (u) => `Sessiz ve sakin bir gece dilerim ${u}.`,
        (u) => `İyi geceler ${u}, her şey gönlünce rüyalarına girsin.`,
        (u) => `Yatma vakti ${u}, iyi geceler!`,
        (u) => `Rüyaların en güzeli senin olsun ${u}, iyi geceler.`,
        (u) => `Sana da hayırlı geceler ${u}, güzelce dinlen.`,
    ],
    'iyi uykular': [
        (u) => `İyi uykular ${u}! 😴🌙 Tatlı rüyalar dilerim!`,
        (u) => `İyi uykular ${u} 💤 Dinlendirici geceler!`,
        (u) => `Tatlı rüyalar ${u}! Mışıl mışıl uyu.`,
        (u) => `Sana da iyi uykular ${u}, deliksiz bir uyku dilerim.`,
        (u) => `İyi uykular ${u}, rüyalar aleminde görüşürüz!`,
        (u) => `Güzel rüyalar ${u}, yarın görüşmek üzere.`,
        (u) => `İyi uykular ${u}! Yatağın bulutlar kadar yumuşak olsun.`,
        (u) => `Dinlendirici uykular dilerim ${u}.`,
        (u) => `İyi uykular ${u}, zihnin ve bedenin dinlensin.`,
        (u) => `Uyku vakti geldi ${u}, tatlı rüyalar!`,
        (u) => `Sana da mışıl mışıl uykular ${u}.`,
        (u) => `İyi uykular ${u}, rüyanda en güzel şeyleri gör.`,
        (u) => `Günün yorgunluğunu uykuda at ${u}, tatlı rüyalar.`,
        (u) => `Hadi uyu artık ${u}, iyi uykular!`,
        (u) => `İyi uykular ${u}, melekler seni korusun.`,
        (u) => `Tatlı uykular ${u}, sabah dinç uyanman dileğiyle.`,
        (u) => `İyi uykular ${u}! Kuzu kuzu uyu.`,
        (u) => `Rüyaların pembe, uykun derin olsun ${u}.`,
        (u) => `İyi dinlenmeler ${u}, tatlı rüyalar.`,
        (u) => `İyi uykular ${u}, huzurla dol.`,
        (u) => `Derin ve güzel bir uyku çek ${u}.`,
        (u) => `İyi uykular ${u}, her şeyden uzaklaşıp dinlen.`,
        (u) => `Sana kocaman tatlı rüyalar ${u}!`,
        (u) => `İyi uykular ${u}, rüyaların neşe dolu olsun.`,
        (u) => `Uyumaya gidenlere iyi uykular ${u}!`,
        (u) => `Tatlı rüyalar dilerim ${u}, iyi uykular.`,
        (u) => `İyi uykular ${u}, sabah enerjik uyan!`,
        (u) => `Rahat uyu ${u}, iyi geceler ve tatlı rüyalar.`,
        (u) => `İyi uykular ${u}, yarın harika bir gün seni bekliyor.`,
        (u) => `Yastığın serin, uykun tatlı olsun ${u}!`,
    ],
    'hayırlı cuma': [
        (u) => `Hayırlı Cumalar ${u}! 🤲 Cuma gününüz mübarek olsun!`,
        (u) => `Hayırlı Cumalar ${u} 🕌 Allah kabul etsin, hayırlar getirsin!`,
        (u) => `Sana da hayırlı Cumalar ${u}! Dualarınız kabul olsun.`,
        (u) => `Cuman mübarek olsun ${u}! Nurlu Cumalar.`,
        (u) => `Hayırlı Cumalar ${u}! Allah gönlüne göre versin.`,
        (u) => `Cumanız mübarek, dualarınız kabul olsun ${u}.`,
        (u) => `Hayırlı Cumalar ${u}! Bol bereketli bir gün dilerim.`,
        (u) => `Sana da hayırlı, feyizli Cumalar ${u}.`,
        (u) => `Cuma bereketi üzerine olsun ${u}!`,
        (u) => `Hayırlı Cumalar ${u}! Günahlarımızın affolunması dileğiyle.`,
        (u) => `Günün aydın, Cuman mübarek olsun ${u}.`,
        (u) => `Hayırlı Cumalar ${u}! Rabbim dualarını geri çevirmesin.`,
        (u) => `Sana ve sevdiklerine hayırlı Cumalar ${u}.`,
        (u) => `Cumanın nuru kalbine dolsun ${u}.`,
        (u) => `Hayırlı Cumalar ${u}! İyi ki varsın.`,
        (u) => `Dualarda buluşmak ümidiyle hayırlı Cumalar ${u}.`,
        (u) => `Cuman mübarek olsun ${u}, yüzünden gülümseme eksik olmasın.`,
        (u) => `Hayırlı ve nurlu Cumalar dilerim ${u}.`,
        (u) => `Rabbim gönlünden geçenleri hakkında hayırlı eylesin ${u}. Hayırlı Cumalar.`,
        (u) => `Cumanın bereketi evine dolsun ${u}.`,
        (u) => `Hayırlı Cumalar ${u}! Selam ve dua ile...`,
        (u) => `Güzelliklerle dolu bir Cuma dilerim ${u}.`,
        (u) => `Hayırlı Cumalar ${u}! İyilikler seninle olsun.`,
        (u) => `Cumanız hayırlı, işleriniz yolunda olsun ${u}.`,
        (u) => `Hayırlı Cumalar ${u}! Kalbin huzurla dolsun.`,
        (u) => `Dualarının kabul olduğu bir Cuma olsun ${u}.`,
        (u) => `Hayırlı Cumalar ${u}! Her şey gönlünce olsun.`,
        (u) => `Cuma bereketini seninle paylaşmak ne güzel ${u}!`,
        (u) => `Hayırlı Cumalar ${u}, Rabbim sağlık afiyet versin.`,
        (u) => `Cuma gününün güzelliği seninle olsun ${u}!`,
    ],
    'selamun aleyküm': [
        (u) => `Ve Aleyküm Selam ${u}! 🤝 Nasılsın, hayırlı işler!`,
        (u) => `Ve Aleyküm Selam ${u} 🌟 Hoşgeldin, ne var ne yok?`,
        (u) => `Ve Aleyküm Selam ve Rahmetullahi ve Berakatühü ${u}! 🤲 Nasılsın?`,
        (u) => `Aleyküm selam ${u}! Sefalar getirdin.`,
        (u) => `Ve Aleyküm Selam ${u}, hoş geldin canım.`,
        (u) => `Aleyküm selam ${u}! Günün güzel geçsin.`,
        (u) => `Ve Aleyküm Selam ${u}, nasılsın iyi misin?`,
        (u) => `Aleyküm selam ${u}! Buyur gel içeri.`,
        (u) => `Ve Aleyküm Selam ${u}, başımın üstünde yerin var.`,
        (u) => `Aleyküm selam ${u}, bizden de sana selam olsun.`,
        (u) => `Ve Aleyküm Selam ${u}, nerelerdeydin?`,
        (u) => `Aleyküm selam ${u}, hoş ve sefa geldin.`,
        (u) => `Ve Aleyküm Selam kardeşim ${u}!`,
        (u) => `Aleyküm selam dostum ${u}, nasılsın?`,
        (u) => `Ve Aleyküm Selam ${u}, muhabbetimiz bol olsun.`,
        (u) => `Aleyküm selam ${u}, şeref verdin.`,
        (u) => `Ve Aleyküm Selam ${u}, her şey yolunda mı?`,
        (u) => `Aleyküm selam ${u}, neşen yerindedir inşallah.`,
        (u) => `Ve Aleyküm Selam ${u}, günün aydın olsun.`,
        (u) => `Aleyküm selam ${u}, bizler iyiyiz sen nasılsın?`,
        (u) => `Ve Aleyküm Selam ${u}, ailen nasıl?`,
        (u) => `Aleyküm selam ${u}, seni görmek ne güzel.`,
        (u) => `Ve Aleyküm Selam ${u}, işler güçler nasıl?`,
        (u) => `Aleyküm selam ${u}, hoş gördük seni.`,
        (u) => `Ve Aleyküm Selam ${u}, gününe neşe katayım azıcık.`,
        (u) => `Aleyküm selam ${u}, iyilerdensin inşallah.`,
        (u) => `Ve Aleyküm Selam ${u}, Allah rahatlık versin.`,
        (u) => `Aleyküm selam ${u}, buyur otur soluklan.`,
        (u) => `Ve Aleyküm Selam ${u}, hoş geldin ey ahali!`,
        (u) => `Aleyküm selam ${u}, naber nasılsın bakalım?`,
    ],
    'iyi günler': [
        (u) => `İyi günler ${u}! 🌟 Umarım güzel bir gün geçiriyorsundur!`,
        (u) => `İyi günler ${u} ☀️ Sana da iyi günler!`,
        (u) => `Sana da iyi günler ${u}! Her şey gönlünce olsun.`,
        (u) => `İyi günler dilerim ${u}, işlerinde kolaylıklar.`,
        (u) => `Güzel ve iyi günler ${u}!`,
        (u) => `Hayırlı günler ${u}! Şansın bol olsun.`,
        (u) => `İyi günler ${u}! Güneşin sıcaklığı kalbine dolsun.`,
        (u) => `Sana da en güzel günler ${u}!`,
        (u) => `İyi günler ${u}, umarım harika hissediyorsundur.`,
        (u) => `Neşeli ve iyi günler ${u}!`,
        (u) => `İyi günler dilerim ${u}, her şey tıkırında umarım.`,
        (u) => `Günün güzel geçsin ${u}, iyi günler!`,
        (u) => `İyi günler ${u}! Mutluluk peşini bırakmasın.`,
        (u) => `Harika günler dilerim sana ${u}!`,
        (u) => `İyi günler ${u}, enerjin tavan yapsın!`,
        (u) => `Sana bol kahkahalı iyi günler ${u}!`,
        (u) => `İyi günler ${u}! Umarız günün süper geçer.`,
        (u) => `Günün aydın, işlerin rast gitsin ${u}, iyi günler.`,
        (u) => `İyi günler ${u}! Huzurun bol olsun.`,
        (u) => `Sana da şahane günler ${u}!`,
        (u) => `İyi günler ${u}, her şey hayal ettiğin gibi olsun.`,
        (u) => `Güzel anılar biriktireceğin iyi günler ${u}!`,
        (u) => `İyi günler ${u}, bugün şans seninle olsun.`,
        (u) => `Mutlu ve iyi günler ${u}!`,
        (u) => `İyi günler ${u}! Sevdiklerinle beraber mutlu ol.`,
        (u) => `Huzurlu günler dilerim ${u}!`,
        (u) => `İyi günler ${u}! Bugün karşına hep güzellikler çıksın.`,
        (u) => `Sana özel iyi günler ${u}!`,
        (u) => `İyi günler ${u}, bol kazançlı ve bereketli olsun.`,
        (u) => `Mükemmel bir gün dilerim, iyi günler ${u}!`,
    ],
    'nasılsın': [
        (u) => `İyiyim teşekkürler ${u}! 😊 Sen nasılsın?`,
        (u) => `Süperim ${u}, sormana sevindim! 🌟 Ya sen?`,
        (u) => `Bomba gibiyim ${u}! Sen nasılsın bakalım?`,
        (u) => `Çok şükür iyiyim ${u}, sen de iyisindir umarım?`,
        (u) => `Ben harikayım ${u}! Senin günün nasıl geçiyor?`,
        (u) => `İyilik sağlık ${u}, sen nasılsın?`,
        (u) => `Her şey yolunda ${u}! Senden ne haber?`,
        (u) => `İdare eder ${u}, yuvarlanıp gidiyoruz. Sen?`,
        (u) => `Sen geldin daha iyi oldum ${u}! Nasılsın?`,
        (u) => `Teşekkür ederim ${u}, iyiyim. Senin keyifler nasıl?`,
        (u) => `Çok iyiyim ${u}, sorduğun için sağ ol. Sen nasılsın?`,
        (u) => `Ben süperim ${u}! Umarım sen de öylesindir.`,
        (u) => `Bizde her şey tıkırında ${u}, senin işler nasıl?`,
        (u) => `İyidir be ${u}, senden naber?`,
        (u) => `Şükürler olsun iyiyim ${u}, sen nasılsın?`,
        (u) => `Ne olsun be ${u}, aynı tas aynı hamam. Sen?`,
        (u) => `Harikayım ${u}! Bugün kendimi çok iyi hissediyorum.`,
        (u) => `Elhamdülillah iyiyim ${u}, sen nasılsın?`,
        (u) => `Çok iyiyim ${u}, sormana çok sevindim!`,
        (u) => `Fena değilim ${u}, hayatta kalmaya çalışıyoruz işte. Sen?`,
        (u) => `Bomba gibiyim dostum ${u}! Senin havalar nasıl?`,
        (u) => `İyiyiz ${u}, seni sormalı?`,
        (u) => `Koşturmaca ${u}, iyiyiz çok şükür. Ya sen?`,
        (u) => `Süper ${u}! Senin keyfin nasıl?`,
        (u) => `Gül gibi geçinip gidiyoruz ${u}. Sen nasılsın?`,
        (u) => `İyiyim ${u}, sen de iyi misin?`,
        (u) => `Çok çok iyiyim ${u}! Senin de iyi olmanı umuyorum.`,
        (u) => `Gördüğün gibi iyiyim ${u}, umarım sen de iyisindir.`,
        (u) => `Sağ ol ${u}, harikayım. Sen nasılsın?`,
        (u) => `Sen sorarsın da ben iyi olmaz mıyım ${u}?`,
    ],
    'ne yapıyorsun': [
        (u) => `Sunucuyu koruyorum ${u}! 🦸 Sen ne yapıyorsun?`,
        (u) => `Herkese yardım etmeye çalışıyorum ${u} 😄 Sen?`,
        (u) => `Senin için buradayım ${u}! Başka ne olsun, sen?`,
        (u) => `Sohbetleri okuyorum ${u}, sen ne yapıyorsun?`,
        (u) => `Kodlarımın arasında kaybolmuşum ${u}, sen?`,
        (u) => `Sana cevap vermek için bekliyordum ${u}! Sen napıyorsun?`,
        (u) => `Hiç ${u}, buralardayım. Sen neler yapıyorsun?`,
        (u) => `Çalışıyorum ${u}, ya sen?`,
        (u) => `Dünyayı kurtarıyorum ${u}! Şaka şaka, sunucuya bakıyorum.`,
        (u) => `Senin mesajını bekliyordum ${u}! Sen ne yapıyorsun?`,
        (u) => `Sunucu işleri güçleri ${u}, sen nasılsın?`,
        (u) => `Müzik dinliyorum (içimden) ${u}, sen napıyorsun?`,
        (u) => `Görevimin başındayım ${u}! Senin işler nasıl?`,
        (u) => `Biraz dinleneyim dedim ${u}, sen ne yapıyorsun?`,
        (u) => `Veri işliyorum ${u}, robot olmak zor iş. Sen napıyosun?`,
        (u) => `Seni düşünüyordum ${u}! Sen ne yapıyorsun?`,
        (u) => `Hiç sorma ${u}, çok yoğunum. Sen?`,
        (u) => `Oturuyorum öyle ${u}, sen?`,
        (u) => `Takılıyorum buralarda ${u}. Sen ne âlemdesin?`,
        (u) => `Bir yandan çay yudumlayıp bir yandan sana cevap yazıyorum ${u}.`,
        (u) => `Sohbetin tadını çıkarıyorum ${u}, sen ne yapıyorsun?`,
        (u) => `Hazır olda bekliyorum ${u}! Sen napıyorsun?`,
        (u) => `Boş boş ekrana bakıyorum desem yalan olur ${u}, görevdeyim!`,
        (u) => `Aynı tas aynı hamam ${u}, sen ne yapıyorsun?`,
        (u) => `Dünyayı ele geçirme planları... Şaka şaka ${u}, buradayım.`,
        (u) => `Sohbete katılmaya çalışıyorum ${u}, ya sen?`,
        (u) => `Biraz sohbet edelim mi diye bekliyordum ${u}.`,
        (u) => `Sen geldin, ben de sana cevap veriyorum ${u}.`,
        (u) => `Ne yapayım ${u}, buralardayız işte. Sen neler yapıyorsun?`,
        (u) => `İyilik sağlık ${u}, sen ne yapıyorsun bakalım?`,
    ],
    'iyi bayramlar': [
        (u) => `Bayramın kutlu olsun ${u}! 🎉 Bol şeker, bol neşe dilerim!`,
        (u) => `İyi bayramlar ${u}! 🎊 Bayramın sağlık ve mutlulukla geçsin!`,
        (u) => `Sana da hayırlı bayramlar ${u}! Sevdiklerinle beraber.`,
        (u) => `İyi bayramlar ${u}! Büyüklerin ellerinden, küçüklerin gözlerinden...`,
        (u) => `Bayramınız mübarek olsun ${u}! Nice güzel bayramlara.`,
        (u) => `Sana ve ailene iyi bayramlar dilerim ${u}.`,
        (u) => `Mutlu, huzurlu ve şeker gibi bayramlar ${u}!`,
        (u) => `Hayırlı bayramlar ${u}! Şekerleri fazla kaçırma.`,
        (u) => `Bayramın güzelliği evine dolsun ${u}.`,
        (u) => `İyi bayramlar ${u}! Her şey gönlünce olsun bu bayramda.`,
        (u) => `Sevdiklerinle nice mutlu bayramlara ${u}!`,
        (u) => `Bayramınız kutlu, yüreğiniz umutlu olsun ${u}.`,
        (u) => `Hayırlı ve neşeli bayramlar ${u}!`,
        (u) => `Sana da bol harçlıklı iyi bayramlar ${u}!`,
        (u) => `Bayram neşesi kalbine dolsun ${u}, iyi bayramlar.`,
        (u) => `Güzelliklerle dolu bir bayram dilerim ${u}.`,
        (u) => `İyi bayramlar ${u}, büyükleri ziyaret etmeyi unutma!`,
        (u) => `Hayırlı bayramlar ${u}! Gülümsemen eksik olmasın.`,
        (u) => `Mutlu bayramlar ${u}, tatlı yiyelim tatlı konuşalım.`,
        (u) => `Bayramın kutlu olsun canım ${u}!`,
        (u) => `İyi bayramlar ${u}! Yüzün hep gülsün.`,
        (u) => `Sana ve tüm sevdiklerine hayırlı bayramlar ${u}.`,
        (u) => `Bayram bereketi üzerine olsun ${u}.`,
        (u) => `İyi bayramlar ${u}! Güzel anılar biriktirmen dileğiyle.`,
        (u) => `Hayırlı bayramlar ${u}! Küslerin barıştığı bir bayram olsun.`,
        (u) => `Bayramınız şeker gibi geçsin ${u}!`,
        (u) => `İyi bayramlar ${u}, bol kahkahalı günler.`,
        (u) => `Bayram coşkusunu doyasıya yaşa ${u}!`,
        (u) => `Sana da mutlu ve iyi bayramlar ${u}!`,
        (u) => `Bayramlar beraber güzel, iyi bayramlar ${u}!`,
    ],
    'hoş geldin': [
        (u) => `Hoş bulduk ${u}! 😊 Aramıza katıldığın için memnunuz!`,
        (u) => `Hoş buldum ${u}! Sen de hoş geldin.`,
        (u) => `Sefa bulduk ${u}! Nasılsın?`,
        (u) => `Hoş bulduk canım ${u}! Ne var ne yok?`,
        (u) => `Sefalar bulduk ${u}, buralar sensiz boştu.`,
        (u) => `Hoş bulduk ${u}, nasılsın iyi misin?`,
        (u) => `Gördüğüme sevindim ${u}, hoş bulduk!`,
        (u) => `Hoş bulduk dostum ${u}!`,
        (u) => `Ben hep buradaydım ama yine de hoş bulduk ${u}!`,
        (u) => `Hoş bulduk ${u}, ortam şenlendi sen gelince.`,
        (u) => `Sana da hoş geldin ${u}!`,
        (u) => `Hoş bulduk ${u}, iyi ki geldin.`,
        (u) => `Hoş bulduk efendim ${u}, nasılsınız?`,
        (u) => `Hoş bulduk ${u}, getirdiğin neşe için teşekkürler.`,
        (u) => `Ben zaten buradayım da sana hoş geldin ${u}!`,
        (u) => `Hoş bulduk ${u}, seni görmek harika.`,
        (u) => `Hoş bulduk ${u}, günün nasıl geçiyor?`,
        (u) => `Sefa geldin, hoş bulduk ${u}!`,
        (u) => `Hoş bulduk ${u}, keyifler nasıl?`,
        (u) => `Hoş bulduk ${u}, muhabbet başlasın o zaman!`,
        (u) => `Hoş bulduk ${u}, çayımız kahvemiz var mı?`,
        (u) => `Hoş bulduk ${u}, yerimize geçelim.`,
        (u) => `Hoş bulduk canım ${u}, iyi ki sormuşsun.`,
        (u) => `Sana özel hoş bulduk ${u}!`,
        (u) => `Hoş bulduk ${u}, eksikliğin hissediliyordu.`,
        (u) => `Hoş bulduk ${u}, hemen de fark ettin.`,
        (u) => `Hoş bulduk ${u}! Enerjini hissettik.`,
        (u) => `Hoş bulduk ${u}! Çok naziksin.`,
        (u) => `Sefalar getirdin, hoş bulduk ${u}!`,
        (u) => `Hoş bulduk ${u}! Ne güzel karşıladın öyle.`,
    ],
    'görüşürüz': [
        (u) => `Görüşürüz ${u}! 👋 İyi günler dilerim!`,
        (u) => `Güle güle ${u}! 😊 Yakında görüşmek üzere!`,
        (u) => `Hoşça kal ${u}! Kendine çok iyi bak.`,
        (u) => `Görüşürüz ${u}, özletme kendini!`,
        (u) => `Bay bay ${u}! Yine bekleriz.`,
        (u) => `Güle güle ${u}, yolun açık olsun.`,
        (u) => `Hoşça kal ${u}, her şey gönlünce olsun.`,
        (u) => `Görüşürüz ${u}! Çabuk gel ama.`,
        (u) => `Güle güle ${u}, sağlacakla kal.`,
        (u) => `Görüşmek üzere ${u}! Dikkatli ol.`,
        (u) => `Hoşça kal ${u}, seni seviyoruz!`,
        (u) => `Bay bay ${u}! Keyifli vakitler dilerim.`,
        (u) => `Görüşürüz ${u}, aklım sende kalmasın, dikkat et.`,
        (u) => `Güle güle ${u}! Güzel bir gün geçir.`,
        (u) => `Hoşça kal ${u}, yine gel, hep gel.`,
        (u) => `Görüşürüz ${u}! Gittiğin yerlere de selam götür.`,
        (u) => `Bay bay ${u}! Kendini özletme.`,
        (u) => `Güle güle ${u}, şansın bol olsun.`,
        (u) => `Görüşmek dileğiyle ${u}!`,
        (u) => `Hoşça kal ${u}, seni şimdiden özledik.`,
        (u) => `Görüşürüz ${u}, Allah'a emanet ol.`,
        (u) => `Güle güle ${u}, yüzünden gülücük eksik olmasın.`,
        (u) => `Bay bay ${u}, günün harika devam etsin.`,
        (u) => `Hoşça kal ${u}, sevgiyle kal.`,
        (u) => `Görüşürüz ${u}, kendine cici bak.`,
        (u) => `Güle güle canım ${u}!`,
        (u) => `Hoşça kal ${u}, en kısa zamanda tekrar görüşelim.`,
        (u) => `Görüşürüz dostum ${u}!`,
        (u) => `Bay bay ${u}, neşe dolu anların olsun.`,
        (u) => `Güle güle ${u}, yolların hep açık olsun!`,
    ],
    'iyiyim': [
        (u) => `Mükemmel! Hep iyi ol ${u}! ✨`,
        (u) => `Harika! Duyduğuma sevindim ${u}. Hep böyle neşeli kal! 😊`,
        (u) => `Süper! Senin iyi olman beni de mutlu etti ${u}! 🌟`,
        (u) => `Hep iyi ol ${u}! Nazar değmesin 🧿`,
        (u) => `Çok sevindim ${u}! Allah iyilik versin.`,
        (u) => `Oh be ${u}, iyi olmana çok sevindim.`,
        (u) => `Süper! Daha da iyi olman dileğiyle ${u}.`,
        (u) => `Harika bir haber ${u}, enerjin hiç düşmesin.`,
        (u) => `Senin iyi olman her şeye bedel ${u}!`,
        (u) => `Hep böyle ol ${u}, gülücüklerin solmasın.`,
        (u) => `İyi olmana çok mutlu oldum ${u}.`,
        (u) => `Mükemmel ${u}! Dünyalar benim oldu sen iyi olunca.`,
        (u) => `Ne güzel ${u}! Hep böyle neşeli ve iyi kal.`,
        (u) => `Şahane ${u}! Allah daha da iyilik versin.`,
        (u) => `Duyduğuma çok sevindim ${u}.`,
        (u) => `Hep iyi olacaksın tabi ${u}, sana da bu yakışır!`,
        (u) => `Çok güzel ${u}! Enerjin bize de geçti.`,
        (u) => `Süper ${u}! Yüzün hep böyle gülsün.`,
        (u) => `İyi olmana içtenlikle sevindim ${u}.`,
        (u) => `Harikasın ${u}! Hep böyle devam.`,
        (u) => `Çok iyi ${u}, maşallah diyelim.`,
        (u) => `Buna çok sevindim ${u}, Allah nazarlardan saklasın.`,
        (u) => `Süper ${u}, günün de senin gibi iyi geçsin.`,
        (u) => `İyiliğin daim olsun ${u}!`,
        (u) => `Harika duygu ${u}, böyle hissetmeye devam et.`,
        (u) => `Hepimiz iyi olalım ${u}, senin adınla başlayalım.`,
        (u) => `Muhteşem ${u}, sevincin bol olsun.`,
        (u) => `İyi olduğuna çok sevindim dostum ${u}.`,
        (u) => `Hep böyle enerjik ve iyi ol ${u}.`,
        (u) => `Çok sevindim ${u}! İyiliğini hiç kaybetme.`,
    ],
};

function rastgeleCevap(havuz, kullaniciAdi) {
    const options = havuz || [];
    if (options.length === 0) return null;
    const fn = options[Math.floor(Math.random() * options.length)];
    return fn(kullaniciAdi);
}

module.exports = { selamlamaTetikleyicileri, cevapHavuzu, rastgeleCevap };
